// 英文单词词汇库 - 按年级分类（简化版，完整版请参考网页版）
export const wordsByGrade = {
  1: [
    { word: 'cat', phonetic: '/kæt/', meaning: '猫' },
    { word: 'dog', phonetic: '/dɔːɡ/', meaning: '狗' },
    { word: 'pig', phonetic: '/pɪɡ/', meaning: '猪' },
    { word: 'duck', phonetic: '/dʌk/', meaning: '鸭子' },
    { word: 'bird', phonetic: '/bɜːrd/', meaning: '鸟' },
    { word: 'apple', phonetic: '/ˈæpəl/', meaning: '苹果' },
    { word: 'banana', phonetic: '/bəˈnɑːnə/', meaning: '香蕉' },
    { word: 'book', phonetic: '/bʊk/', meaning: '书' },
    { word: 'pencil', phonetic: '/ˈpensəl/', meaning: '铅笔' },
    { word: 'one', phonetic: '/wʌn/', meaning: '一' },
    { word: 'two', phonetic: '/tuː/', meaning: '二' },
    { word: 'three', phonetic: '/θriː/', meaning: '三' },
    { word: 'red', phonetic: '/red/', meaning: '红色' },
    { word: 'blue', phonetic: '/bluː/', meaning: '蓝色' },
    { word: 'head', phonetic: '/hed/', meaning: '头' },
    { word: 'hand', phonetic: '/hænd/', meaning: '手' },
    { word: 'school', phonetic: '/skuːl/', meaning: '学校' },
    { word: 'teacher', phonetic: '/ˈtiːtʃər/', meaning: '老师' },
    { word: 'student', phonetic: '/ˈstuːdənt/', meaning: '学生' },
    { word: 'desk', phonetic: '/desk/', meaning: '课桌' }
  ],
  2: [
    { word: 'monkey', phonetic: '/ˈmʌŋki/', meaning: '猴子' },
    { word: 'tiger', phonetic: '/ˈtaɪɡər/', meaning: '老虎' },
    { word: 'elephant', phonetic: '/ˈeləfənt/', meaning: '大象' },
    { word: 'strawberry', phonetic: '/ˈstrɔːberi/', meaning: '草莓' },
    { word: 'watermelon', phonetic: '/ˈwɔːtərmelən/', meaning: '西瓜' },
    { word: 'bag', phonetic: '/bæɡ/', meaning: '包' },
    { word: 'pen', phonetic: '/pen/', meaning: '钢笔' },
    { word: 'notebook', phonetic: '/ˈnoʊtbʊk/', meaning: '笔记本' },
    { word: 'eleven', phonetic: '/ɪˈlevən/', meaning: '十一' },
    { word: 'twelve', phonetic: '/twelv/', meaning: '十二' },
    { word: 'pink', phonetic: '/pɪŋk/', meaning: '粉红色' },
    { word: 'brown', phonetic: '/braʊn/', meaning: '棕色' },
    { word: 'ear', phonetic: '/ɪr/', meaning: '耳朵' },
    { word: 'hair', phonetic: '/her/', meaning: '头发' },
    { word: 'home', phonetic: '/hoʊm/', meaning: '家' },
    { word: 'bedroom', phonetic: '/ˈbedruːm/', meaning: '卧室' },
    { word: 'kitchen', phonetic: '/ˈkɪtʃən/', meaning: '厨房' },
    { word: 'father', phonetic: '/ˈfɑːðər/', meaning: '父亲' },
    { word: 'mother', phonetic: '/ˈmʌðər/', meaning: '母亲' },
    { word: 'sister', phonetic: '/ˈsɪstər/', meaning: '姐妹' }
  ],
  3: [
    { word: 'kangaroo', phonetic: '/ˌkæŋɡəˈruː/', meaning: '袋鼠' },
    { word: 'giraffe', phonetic: '/dʒəˈræf/', meaning: '长颈鹿' },
    { word: 'bear', phonetic: '/ber/', meaning: '熊' },
    { word: 'rabbit', phonetic: '/ˈræbɪt/', meaning: '兔子' },
    { word: 'kiwi', phonetic: '/ˈkiːwi/', meaning: '猕猴桃' },
    { word: 'mango', phonetic: '/ˈmæŋɡoʊ/', meaning: '芒果' },
    { word: 'pineapple', phonetic: '/ˈpaɪnæpəl/', meaning: '菠萝' },
    { word: 'glue', phonetic: '/ɡluː/', meaning: '胶水' },
    { word: 'scissors', phonetic: '/ˈsɪzərz/', meaning: '剪刀' },
    { word: 'thirty', phonetic: '/ˈθɜːrti/', meaning: '三十' },
    { word: 'circle', phonetic: '/ˈsɜːrkəl/', meaning: '圆形' },
    { word: 'square', phonetic: '/skwer/', meaning: '正方形' },
    { word: 'hot', phonetic: '/hɑːt/', meaning: '热的' },
    { word: 'cold', phonetic: '/koʊld/', meaning: '冷的' },
    { word: 'spring', phonetic: '/sprɪŋ/', meaning: '春天' },
    { word: 'summer', phonetic: '/ˈsʌmər/', meaning: '夏天' },
    { word: 'China', phonetic: '/ˈtʃaɪnə/', meaning: '中国' },
    { word: 'America', phonetic: '/əˈmerɪkə/', meaning: '美国' },
    { word: 'he', phonetic: '/hi/', meaning: '他' },
    { word: 'she', phonetic: '/ʃi/', meaning: '她' }
  ],
  4: [
    { word: 'squirrel', phonetic: '/ˈskwɪrəl/', meaning: '松鼠' },
    { word: 'deer', phonetic: '/dɪr/', meaning: '鹿' },
    { word: 'crocodile', phonetic: '/ˈkrɑːkədaɪl/', meaning: '鳄鱼' },
    { word: 'snake', phonetic: '/sneɪk/', meaning: '蛇' },
    { word: 'shark', phonetic: '/ʃɑːrk/', meaning: '鲨鱼' },
    { word: 'avocado', phonetic: '/ˌævəˈkɑːdoʊ/', meaning: '牛油果' },
    { word: 'apricot', phonetic: '/ˈeɪprɪkɑːt/', meaning: '杏' },
    { word: 'umbrella', phonetic: '/ʌmˈbrelə/', meaning: '伞' },
    { word: 'glasses', phonetic: '/ˈɡlæsɪz/', meaning: '眼镜' },
    { word: 'first', phonetic: '/fɜːrst/', meaning: '第一' },
    { word: 'left', phonetic: '/left/', meaning: '左边' },
    { word: 'right', phonetic: '/raɪt/', meaning: '右边' },
    { word: 'January', phonetic: '/ˈdʒænjueri/', meaning: '一月' },
    { word: 'February', phonetic: '/ˈfebrueri/', meaning: '二月' },
    { word: 'fast', phonetic: '/fæst/', meaning: '快的' },
    { word: 'slow', phonetic: '/sloʊ/', meaning: '慢的' },
    { word: 'interesting', phonetic: '/ˈɪntrəstɪŋ/', meaning: '有趣的' },
    { word: 'boring', phonetic: '/ˈbɔːrɪŋ/', meaning: '无聊的' },
    { word: 'easy', phonetic: '/ˈiːzi/', meaning: '容易的' },
    { word: 'difficult', phonetic: '/ˈdɪfɪkəlt/', meaning: '困难的' }
  ],
  5: [
    { word: 'beaver', phonetic: '/ˈbiːvər/', meaning: '海狸' },
    { word: 'otter', phonetic: '/ˈɑːtər/', meaning: '水獭' },
    { word: 'turtle', phonetic: '/ˈtɜːrtəl/', meaning: '乌龟' },
    { word: 'dolphin', phonetic: '/ˈdɑːlfɪn/', meaning: '海豚' },
    { word: 'whale', phonetic: '/weɪl/', meaning: '鲸鱼' },
    { word: 'pomegranate', phonetic: '/ˈpɑːmɪɡrænɪt/', meaning: '石榴' },
    { word: 'coconut', phonetic: '/ˈkoʊkənʌt/', meaning: '椰子' },
    { word: 'camera', phonetic: '/ˈkæmərə/', meaning: '相机' },
    { word: 'computer', phonetic: '/kəmˈpjuːtər/', meaning: '电脑' },
    { word: 'keyboard', phonetic: '/ˈkiːbɔːrd/', meaning: '键盘' },
    { word: 'often', phonetic: '/ˈɔːfən/', meaning: '经常' },
    { word: 'usually', phonetic: '/ˈjuːʒuəli/', meaning: '通常' },
    { word: 'never', phonetic: '/ˈnevər/', meaning: '从不' },
    { word: 'always', phonetic: '/ˈɔːlweɪz/', meaning: '总是' },
    { word: 'famous', phonetic: '/ˈfeɪməs/', meaning: '著名的' },
    { word: 'popular', phonetic: '/ˈpɑːpjələr/', meaning: '受欢迎的' },
    { word: 'important', phonetic: '/ɪmˈpɔːrtənt/', meaning: '重要的' },
    { word: 'useful', phonetic: '/ˈjuːsfəl/', meaning: '有用的' },
    { word: 'environment', phonetic: '/ɪnˈvaɪrənmənt/', meaning: '环境' },
    { word: 'nature', phonetic: '/ˈneɪtʃər/', meaning: '自然' }
  ],
  6: [
    { word: 'porcupine', phonetic: '/ˈpɔːrkjupaɪn/', meaning: '豪猪' },
    { word: 'anteater', phonetic: '/ˈæntiːtər/', meaning: '食蚁兽' },
    { word: 'mongoose', phonetic: '/ˈmɑːŋɡuːs/', meaning: '猫鼬' },
    { word: 'chimpanzee', phonetic: '/ˌtʃɪmpænˈziː/', meaning: '黑猩猩' },
    { word: 'gorilla', phonetic: '/ɡəˈrɪlə/', meaning: '大猩猩' },
    { word: 'passion-fruit', phonetic: '/ˈpæʃən fruːt/', meaning: '百香果' },
    { word: 'persimmon', phonetic: '/pərˈsɪmən/', meaning: '柿子' },
    { word: 'telephone', phonetic: '/ˈtelɪfoʊn/', meaning: '电话' },
    { word: 'television', phonetic: '/ˈtelɪvɪʒən/', meaning: '电视' },
    { word: 'fridge', phonetic: '/frɪdʒ/', meaning: '冰箱' },
    { word: 'hard-working', phonetic: '/ˌhɑːrd ˈwɜːrkɪŋ/', meaning: '勤劳的' },
    { word: 'lazy', phonetic: '/ˈleɪzi/', meaning: '懒惰的' },
    { word: 'kind', phonetic: '/kaɪnd/', meaning: '善良的' },
    { word: 'strict', phonetic: '/strɪkt/', meaning: '严格的' },
    { word: 'friendly', phonetic: '/ˈfrendli/', meaning: '友好的' },
    { word: 'generous', phonetic: '/ˈdʒenərəs/', meaning: '慷慨的' },
    { word: 'humorous', phonetic: '/ˈhjuːmərəs/', meaning: '幽默的' },
    { word: 'serious', phonetic: '/ˈsɪriəs/', meaning: '严肃的' },
    { word: 'patient', phonetic: '/ˈpeɪʃənt/', meaning: '耐心的' },
    { word: 'impatient', phonetic: '/ɪmˈpeɪʃənt/', meaning: '不耐心的' }
  ],
  7: [
    { word: 'pest', phonetic: '/pest/', meaning: '害虫' },
    { word: 'cricket', phonetic: '/ˈkrɪkɪt/', meaning: '蟋蟀' },
    { word: 'butterfly', phonetic: '/ˈbʌtərflaɪ/', meaning: '蝴蝶' },
    { word: 'mosquito', phonetic: '/məˈskiːtoʊ/', meaning: '蚊子' },
    { word: 'ant', phonetic: '/ænt/', meaning: '蚂蚁' },
    { word: 'blueberry', phonetic: '/ˈbluːberi/', meaning: '蓝莓' },
    { word: 'blackberry', phonetic: '/ˈblækberi/', meaning: '黑莓' },
    { word: 'ballet', phonetic: '/bæˈleɪ/', meaning: '芭蕾舞' },
    { word: 'opera', phonetic: '/ˈɑːpərə/', meaning: '歌剧' },
    { word: 'concert', phonetic: '/ˈkɑːnsərt/', meaning: '音乐会' },
    { word: 'kilometer', phonetic: '/kɪˈlɑːmɪtər/', meaning: '公里' },
    { word: 'meter', phonetic: '/ˈmiːtər/', meaning: '米' },
    { word: 'gram', phonetic: '/ɡræm/', meaning: '克' },
    { word: 'million', phonetic: '/ˈmɪljən/', meaning: '百万' },
    { word: 'seldom', phonetic: '/ˈseldəm/', meaning: '很少' },
    { word: 'rarely', phonetic: '/ˈrerli/', meaning: '罕见地' },
    { word: 'occasionally', phonetic: '/əˈkeɪʒənəli/', meaning: '偶尔' },
    { word: 'honest', phonetic: '/ˈɑːnɪst/', meaning: '诚实的' },
    { word: 'polite', phonetic: '/pəˈlaɪt/', meaning: '礼貌的' },
    { word: 'rude', phonetic: '/ruːd/', meaning: '粗鲁的' }
  ],
  8: [
    { word: 'centipede', phonetic: '/ˈsentɪpiːd/', meaning: '蜈蚣' },
    { word: 'millipede', phonetic: '/ˈmɪlɪpiːd/', meaning: '千足虫' },
    { word: 'spider', phonetic: '/ˈspaɪdər/', meaning: '蜘蛛' },
    { word: 'scorpion', phonetic: '/ˈskɔːrpiən/', meaning: '蝎子' },
    { word: 'jellyfish', phonetic: '/ˈdʒelifɪʃ/', meaning: '水母' },
    { word: 'dragon-fruit', phonetic: '/ˈdræɡən fruːt/', meaning: '火龙果' },
    { word: 'poetry', phonetic: '/ˈpoʊətri/', meaning: '诗歌' },
    { word: 'novel', phonetic: '/ˈnɑːvəl/', meaning: '小说' },
    { word: 'interview', phonetic: '/ˈɪntərvjuː/', meaning: '采访' },
    { word: 'athlete', phonetic: '/ˈæθliːt/', meaning: '运动员' },
    { word: 'coach', phonetic: '/koʊtʃ/', meaning: '教练' },
    { word: 'champion', phonetic: '/ˈtʃæmpiən/', meaning: '冠军' },
    { word: 'race', phonetic: '/reɪs/', meaning: '比赛' },
    { word: 'competition', phonetic: '/ˌkɑːmpəˈtɪʃən/', meaning: '竞争' },
    { word: 'defeat', phonetic: '/dɪˈfiːt/', meaning: '失败' },
    { word: 'win', phonetic: '/wɪn/', meaning: '赢' },
    { word: 'lose', phonetic: '/luːz/', meaning: '输' },
    { word: 'achieve', phonetic: '/əˈtʃiːv/', meaning: '实现' },
    { word: 'success', phonetic: '/səkˈses/', meaning: '成功' },
    { word: 'failure', phonetic: '/ˈfeɪljər/', meaning: '失败' }
  ],
  9: [
    { word: 'octopus', phonetic: '/ˈɑːktəpəs/', meaning: '章鱼' },
    { word: 'squid', phonetic: '/skwɪd/', meaning: '鱿鱼' },
    { word: 'cuttlefish', phonetic: '/ˈkʌtəlfɪʃ/', meaning: '乌贼' },
    { word: 'lobster', phonetic: '/ˈlɑːbstər/', meaning: '龙虾' },
    { word: 'crab', phonetic: '/kræb/', meaning: '螃蟹' },
    { word: 'walnut', phonetic: '/ˈwɔːlnʌt/', meaning: '核桃' },
    { word: 'almond', phonetic: '/ˈɑːmənd/', meaning: '杏仁' },
    { word: 'biography', phonetic: '/baɪˈɑːɡrəfi/', meaning: '传记' },
    { word: 'audience', phonetic: '/ˈɔːdiəns/', meaning: '观众' },
    { word: 'spectator', phonetic: '/ˈspekteɪtər/', meaning: '观众' },
    { word: 'record', phonetic: '/ˈrekərd/', meaning: '记录' },
    { word: 'contest', phonetic: '/ˈkɑːntest/', meaning: '竞赛' },
    { word: 'effort', phonetic: '/ˈefərt/', meaning: '努力' },
    { word: 'progress', phonetic: '/ˈprɑːɡres/', meaning: '进步' },
    { word: 'improve', phonetic: '/ɪmˈpruːv/', meaning: '改进' },
    { word: 'review', phonetic: '/rɪˈvjuː/', meaning: '复习' },
    { word: 'prepare', phonetic: '/prɪˈper/', meaning: '准备' },
    { word: 'graduate', phonetic: '/ˈɡrædʒuət/', meaning: '毕业' },
    { word: 'brave', phonetic: '/breɪv/', meaning: '勇敢的' },
    { word: 'shy', phonetic: '/ʃaɪ/', meaning: '害羞的' }
  ],
  10: [
    { word: 'dinosaur', phonetic: '/ˈdaɪnəsɔːr/', meaning: '恐龙' },
    { word: 'mammoth', phonetic: '/ˈmæməθ/', meaning: '猛犸象' },
    { word: 'dodo', phonetic: '/ˈdoʊdoʊ/', meaning: '渡渡鸟' },
    { word: 'pterosaur', phonetic: '/ˈterəsɔːr/', meaning: '翼龙' },
    { word: 'pistachio', phonetic: '/pɪˈstɑːʃioʊ/', meaning: '开心果' },
    { word: 'macadamia', phonetic: '/ˌmækəˈdeɪmiə/', meaning: '澳洲坚果' },
    { word: 'pecan', phonetic: '/pɪˈkɑːn/', meaning: '山核桃' },
    { word: 'cashew', phonetic: '/ˈkæʃuː/', meaning: '腰果' },
    { word: 'philosophy', phonetic: '/fɪˈlɑːsəfi/', meaning: '哲学' },
    { word: 'psychology', phonetic: '/saɪˈkɑːlədʒi/', meaning: '心理学' },
    { word: 'sociology', phonetic: '/ˌsoʊsiˈɑːlədʒi/', meaning: '社会学' },
    { word: 'anthropology', phonetic: '/ˌænθrəˈpɑːlədʒi/', meaning: '人类学' },
    { word: 'archaeology', phonetic: '/ˌɑːrkiˈɑːlədʒi/', meaning: '考古学' },
    { word: 'astronomy', phonetic: '/əˈstrɑːnəmi/', meaning: '天文学' },
    { word: 'geology', phonetic: '/dʒiˈɑːlədʒi/', meaning: '地质学' },
    { word: 'meteorology', phonetic: '/ˌmiːtiərəˈlɑːlədʒi/', meaning: '气象学' },
    { word: 'oceanography', phonetic: '/ˌoʊʃənˈɑːɡrəfi/', meaning: '海洋学' },
    { word: 'ecology', phonetic: '/iˈkɑːlədʒi/', meaning: '生态学' },
    { word: 'botany', phonetic: '/ˈbɑːtəni/', meaning: '植物学' },
    { word: 'zoology', phonetic: '/zoʊˈɑːlədʒi/', meaning: '动物学' }
  ],
  11: [
    { word: 'quantum', phonetic: '/ˈkwɑːntəm/', meaning: '量子' },
    { word: 'relativity', phonetic: '/ˌreləˈtɪvəti/', meaning: '相对论' },
    { word: 'thermodynamics', phonetic: '/ˌθɜːrmoʊdaɪˈnæmɪks/', meaning: '热力学' },
    { word: 'electromagnetism', phonetic: '/ɪˌlektrəˈmæɡnətɪzəm/', meaning: '电磁学' },
    { word: 'mechanics', phonetic: '/məˈkænɪks/', meaning: '力学' },
    { word: 'optics', phonetic: '/ˈɑːptɪks/', meaning: '光学' },
    { word: 'acoustics', phonetic: '/əˈkuːstɪks/', meaning: '声学' },
    { word: 'crystallography', phonetic: '/ˌkrɪstəˈlɑːɡrəfi/', meaning: '晶体学' },
    { word: 'spectroscopy', phonetic: '/spekˈtrɑːskəpi/', meaning: '分光学' },
    { word: 'chromatography', phonetic: '/ˌkroʊmətˈɑːɡrəfi/', meaning: '色谱法' },
    { word: 'immunology', phonetic: '/ˌɪmjəˈnɑːlədʒi/', meaning: '免疫学' },
    { word: 'virology', phonetic: '/vaɪˈrɑːlədʒi/', meaning: '病毒学' },
    { word: 'bacteriology', phonetic: '/ˌbæktɪriˈɑːlədʒi/', meaning: '细菌学' },
    { word: 'parasitology', phonetic: '/ˌpærəsɪˈtɑːlədʒi/', meaning: '寄生虫学' },
    { word: 'entomology', phonetic: '/ˌentəˈmɑːlədʒi/', meaning: '昆虫学' },
    { word: 'ornithology', phonetic: '/ˌɔːrnɪˈθɑːlədʒi/', meaning: '鸟类学' },
    { word: 'ichthyology', phonetic: '/ˌɪkθiˈɑːlədʒi/', meaning: '鱼类学' },
    { word: 'herpetology', phonetic: '/ˌhɜːrpɪˈtɑːlədʒi/', meaning: '爬虫学' },
    { word: 'malacology', phonetic: '/ˌmæləˈkɑːlədʒi/', meaning: '软体动物学' },
    { word: 'arachnology', phonetic: '/ˌærækˈnɑːlədʒi/', meaning: '蛛形学' }
  ],
  12: [
    { word: 'epistemology', phonetic: '/ɪˌpɪstəˈmɑːlədʒi/', meaning: '认识论' },
    { word: 'ontology', phonetic: '/ɑːnˈtɑːlədʒi/', meaning: '本体论' },
    { word: 'metaphysics', phonetic: '/ˌmetəˈfɪzɪks/', meaning: '形而上学' },
    { word: 'aesthetics', phonetic: '/esˈθetɪks/', meaning: '美学' },
    { word: 'ethics', phonetic: '/ˈeθɪks/', meaning: '伦理学' },
    { word: 'logic', phonetic: '/ˈlɑːdʒɪk/', meaning: '逻辑学' },
    { word: 'phenomenology', phonetic: '/fɪˌnɑːməˈnɑːlədʒi/', meaning: '现象学' },
    { word: 'hermeneutics', phonetic: '/ˌhɜːrməˈnuːtɪks/', meaning: '解释学' },
    { word: 'pragmatism', phonetic: '/ˈpræɡmətɪzəm/', meaning: '实用主义' },
    { word: 'existentialism', phonetic: '/ˌeɡzɪˈstenʃəlɪzəm/', meaning: '存在主义' },
    { word: 'phenomenalism', phonetic: '/fɪˈnɑːmənəlɪzəm/', meaning: '现象主义' },
    { word: 'nominalism', phonetic: '/ˈnɑːmɪnəlɪzəm/', meaning: '唯名论' },
    { word: 'realism', phonetic: '/ˈriːəlɪzəm/', meaning: '实在论' },
    { word: 'idealism', phonetic: '/aɪˈdiːəlɪzəm/', meaning: '理想主义' },
    { word: 'materialism', phonetic: '/məˈtɪriəlɪzəm/', meaning: '唯物主义' },
    { word: 'determinism', phonetic: '/dɪˈtɜːrmɪnɪzəm/', meaning: '决定论' },
    { word: 'indeterminism', phonetic: '/ˌɪndɪˈtɜːrmɪnɪzəm/', meaning: '非决定论' },
    { word: 'compatibilism', phonetic: '/ˌkɑːmpætɪˈbɪlɪzəm/', meaning: '相容论' },
    { word: 'libertarianism', phonetic: '/ˌlɪbərˈteriənɪzəm/', meaning: '自由意志论' },
    { word: 'fatalism', phonetic: '/ˈfeɪtəlɪzəm/', meaning: '宿命论' }
  ]
};
